<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="2" time="0.114" timestamp="2021-09-07T17:51:42.548792" hostname="ukasz-desktop"><testcase classname="test_sample1" name="test_file1_method1" time="0.003"><failure message="AssertionError: test failed&#10;assert 5 == 6&#10;  +5&#10;  -6">@pytest.mark.set1
    def test_file1_method1():
    	x = 5
    	y = 6
    	assert x + 1 == y,"test failed"
&gt;   	assert x == y,"test failed"
E    AssertionError: test failed
E    assert 5 == 6
E      +5
E      -6

test_sample1.py:7: AssertionError</failure></testcase><testcase classname="test_sample1" name="test_file1_method2" time="0.002" /></testsuite></testsuites>